apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-custom-scc
  namespace: cfos-ingress
subjects:
  - kind: ServiceAccount
    name: cfos-serviceaccount
    namespace: cfos-ingress
roleRef:
  kind: ClusterRole
  name: use-custom-scc
  apiGroup: rbac.authorization.k8s.io

