apiVersion: v1
kind: Service
metadata:
  name: cfos7210250-service
  annotations:
    protectedClusterIPSVCName: goweb
    metallb.universe.tf/loadBalancerIPs: 10.0.0.4
    service.beta.kubernetes.io/azure-dns-label-name: k8strainingmaster1
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    name: rest
    targetPort: 80
  - port: 8888
    name: cfos7210250-service-8888
    targetPort: 8888
  selector:
    app: cfos
  type: LoadBalancer
