apiVersion: v1
kind: Service
metadata:
  name: cfos7210250-service
  annotations:
    managedByController: fortinetcfos
    metallb.universe.tf/loadBalancerIPs: 10.0.0.4
    service.beta.kubernetes.io/azure-dns-label-name: k8strainingmaster1
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    name: rest
    targetPort: 80
  - port: 8889
    name: cfos-nginx-1
    targetPort: 8889
    protocol: TCP
  - port: 8888
    name: cfos-goweb-2
    targetPort: 8888
    protocol: TCP
  - port: 8887
    name: cfos-goweb-3
    targetPort: 8887
    protocol: TCP
  selector:
    app: cfos
  type: LoadBalancer
